# Generated by Django 3.1.2 on 2023-06-25 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carrito_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.ForeignKey(default='SOLICITUD INGRESADA', on_delete=django.db.models.deletion.CASCADE, to='core.seguimiento'),
        ),
    ]
