# Generated by Django 3.1.2 on 2023-06-12 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empleado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='v_cargo',
            new_name='cargo',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='v_descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='v_imagen',
            new_name='imagen_empleado',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='v_nombre_empleado',
            new_name='nombre_empleado',
        ),
    ]
