# Generated by Django 3.1.2 on 2023-06-12 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230612_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='descripcion',
            new_name='descripcion_empleado',
        ),
    ]
