# Generated by Django 3.1.2 on 2023-06-25 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_orden_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='Item',
        ),
    ]
