# Generated by Django 3.1.2 on 2023-06-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_itemorden'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorden',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
