# Generated by Django 3.1.2 on 2023-06-25 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_itemorden_cantidad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemOrden',
        ),
    ]
