# Generated by Django 3.1.2 on 2023-06-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230625_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='productos',
            field=models.ManyToManyField(through='core.ItemOrden', to='core.Producto'),
        ),
    ]
