# Generated by Django 3.1.2 on 2023-06-25 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20230624_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariocustom',
            name='direccion_casa',
        ),
    ]
